# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 19:51
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('energia_activa', models.IntegerField()),
                ('energia_aparente', models.IntegerField()),
                ('demanda', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fotografia', models.ImageField(upload_to=dashboard.models.get_imagen_nodo_dir)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Nodo')),
            ],
        ),
        migrations.AddField(
            model_name='medicion',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Nodo'),
        ),
    ]
