# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 22:21
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('char_rep', models.CharField(max_length=2)),
                ('integer_rep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.IntegerField()),
                ('apparent', models.IntegerField()),
                ('demand', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('char_rep', models.CharField(max_length=2)),
                ('integer_rep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('photography', models.ImageField(blank=True, null=True, upload_to=dashboard.models.get_imagen_nodo_dir)),
                ('location', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='dashboard.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='TariffSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('fixed', models.FloatField()),
                ('peak', models.FloatField()),
                ('rest', models.FloatField()),
                ('valley', models.FloatField()),
                ('power', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10'), (11, b'11'), (12, b'12'), (13, b'13'), (14, b'14'), (15, b'15'), (16, b'16'), (17, b'17'), (18, b'18'), (19, b'19'), (20, b'20'), (21, b'21'), (22, b'22'), (23, b'23')])),
                ('mins', models.IntegerField(choices=[(0, b'0'), (15, b'15'), (30, b'30'), (45, b'45')])),
                ('char_rep', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('char_rep', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Supplier'),
        ),
        migrations.AddField(
            model_name='measure',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Month'),
        ),
        migrations.AddField(
            model_name='measure',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Node'),
        ),
        migrations.AddField(
            model_name='measure',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Time'),
        ),
        migrations.AddField(
            model_name='measure',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Year'),
        ),
    ]
