# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='datetime_str',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
