# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 04:21
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160326_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.get_imagen_nodo_dir),
        ),
    ]
