# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_measure_datetime_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerFactorTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_power_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('min_power_factor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('charge_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='TariffValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_value', models.FloatField()),
                ('charge_loss_of_transformation', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='TariffVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('consume_begins', models.TimeField()),
                ('consume_ends', models.TimeField()),
                ('is_fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tariffschedule',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='tariffschedule',
            name='peak',
        ),
        migrations.RemoveField(
            model_name='tariffschedule',
            name='power',
        ),
        migrations.RemoveField(
            model_name='tariffschedule',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='tariffschedule',
            name='valley',
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together=set([('node', 'year', 'month', 'day', 'time')]),
        ),
        migrations.AddField(
            model_name='tariffvalues',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TariffVariables'),
        ),
        migrations.AddField(
            model_name='tariffschedule',
            name='power_factor_tariff_values',
            field=models.ManyToManyField(to='dashboard.PowerFactorTariff'),
        ),
        migrations.AddField(
            model_name='tariffschedule',
            name='tariff_values',
            field=models.ManyToManyField(to='dashboard.TariffValues'),
        ),
    ]
