# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161203_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TariffValues',
            new_name='TariffValue',
        ),
        migrations.RenameModel(
            old_name='TariffVariables',
            new_name='TariffVariable',
        ),
    ]
