# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20161203_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffvariable',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
