# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 05:11
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160330_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='coordenada',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
