# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20161203_1200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together=set([('day',), ('char_rep',)]),
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together=set([('month',), ('char_rep',)]),
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together=set([('hour', 'mins'), ('char_rep',)]),
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together=set([('year',), ('char_rep',)]),
        ),
    ]
