# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20161205_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerfactortariff',
            name='charge_value_to_max',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tariffvariable',
            name='over_max_demand',
            field=models.BooleanField(default=False),
        ),
    ]
