# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20161214_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffvariable',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
