# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_tariffvariable_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffvariable',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
