# -*- coding: utf-8 -*-

"""
Django settings for endash project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from endash.settings import *

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',
        'NAME': 'lennin92$endash',
        'USER': 'lennin92$endash',
        'PASSWORD': 'asdf123321fdsa',
        'HOST': '192.168.2.2',
        'PORT': '3306',
    }
}
